run('C:\Users\Administrator\Desktop\AA2Jerry\01Import\go')
run('C:\Users\Administrator\Desktop\AA2Jerry\02Concat\go')
run('C:\Users\Administrator\Desktop\AA2Jerry\03SliceTiming\go')
run('C:\Users\Administrator\Desktop\AA2Jerry\04Motion\go')
run('C:\Users\Administrator\Desktop\AA2Jerry\05Warp2Norm\go')
run('C:\Users\Administrator\Desktop\AA2Jerry\06Smooth\go')
