% these files could be generated by python script
% there should be a separate file for each run for each subject
%     if not, say s0215_r01_multiconds.mat is missing, swmt_s0215_r01.nii processing will be skipped/ignored
% The order of conditions/names should be the same(* see below) across subjects and does not need to follow the presentation order
%     e.g., subject 1 has conditions C A T, subject 2 should have the same conditions C A T; the actual presentation might be random
%     *However, the number of conditions could be different for different runs/subjects
%       say s1101r01 has C A, s1101r02 has A T, s1102r03 has C A T.  This is allowed but the betas are a bit confusing:
%       Basically, in the design matrix, each beta corresponding to a column for each condition for each run
%       if every subject/run is in same condition number and order, easy to know which beta is which condition
%       with different conditions for each run (which generates different number of betas)
%       better keep the condition order the same, making it a bit easier to track betas
% If you enter a single number for the durations it will be assumed that all trials conform to this duration. 
% If you have multiple different durations, then the number must match the number of onset times.    
% e.g.,  (note s0215r02 does not have jol3 condition)
clear
names{1}='jol2';
onsets{1}=[27.0, 195.0, 153.0, 234.0, 111.0, 66.0, 48.0, 246.0, 231.0, 201.0];
durations{1}=[0];
names{2}='jol3';
onsets{2}=[30.0, 81.0, 213.0, 165.0, 36.0, 189.0, 204.0, 78.0, 255.0, 228.0, 249.0, 90.0, 6.0, 216.0, 54.0, 75.0, 162.0, 168.0, 63.0, 180.0];
durations{2}=[0];
names{3}='arrow';
onsets{3}=[120, 270];
durations{3}=[30, 30];
save s0215_r01_multiconds.mat
clear
names{1}='jol2';
onsets{1}=[27.0, 195.0, 153.0, 234.0, 111.0, 66.0, 48.0, 246.0, 231.0, 201.0];
durations{1}=[0];
names{2}='arrow';
onsets{2}=[120, 270];
durations{2}=[30, 30];
save s0215_r02_multiconds.mat
clear
% next subject-run