% this file could be generated by python script
% this is an example of mixed design (in a run there are both events and blocks)
% there should be a separate file for each run for each subject
% The order of conditions/names should be the same across subjects and does not need to follow the presentation order
% e.g., subject 1 has conditions C A T, subject 2 should have the same conditions; the actual presentation might be random
% If you enter a single number for the durations it will be assumed that all trials conform to this duration. 
% If you have multiple different durations, then the number must match the number of onset times.
clear
names{1}='JOL2';
onsets{1}=[27.0, 195.0, 153.0, 234.0, 111.0, 66.0, 48.0, 231.0, 201.0];
durations{1}=[0];
names{2}='JOL3';
onsets{2}=[30.0, 81.0, 213.0, 165.0, 36.0, 189.0, 204.0, 78.0, 228.0, 90.0, 6.0, 216.0, 54.0, 75.0, 162.0, 168.0, 63.0, 180.0];
durations{2}=[0];
names{3}='JOL7';
onsets{3}=[105.0, 117.0, 42.0, 186.0, 240.0, 84.0, 156.0, 33.0, 102.0, 87.0];
durations{3}=[0];
names{4}='JOL8';
onsets{4}=[24.0];
durations{4}=[0];
names{5}='RcgHit';
onsets{5}=[30.0, 93.0, 165.0, 12.0, 15.0, 27.0, 222.0, 195.0, 153.0, 24.0, 117.0, 111.0, 42.0, 186.0, 36.0, 108.0, 78.0, 69.0, 6.0, 48.0, 216.0, 54.0, 162.0, 102.0, 168.0, 63.0, 231.0, 87.0, 177.0, 201.0];
durations{5}=[0];
names{6}='RcgMiss';
onsets{6}=[28.0, 27.0];
durations{6}=[0];
names{7}='JOL2RcgHit';
onsets{7}=[27.0, 195.0, 153.0, 111.0, 48.0, 231.0, 201.0];
durations{7}=[0];
names{8}='JOL3RcgHit';
onsets{8}=[30.0, 165.0, 36.0, 78.0, 29.0, 6.0, 216.0, 54.0, 162.0, 168.0, 63.0];
durations{8}=[0];
names{9}='JOL7RcgHit';
onsets{9}=[25.0, 117.0, 42.0, 186.0, 24.0, 102.0, 87.0];
durations{9}=[0];
names{10}='JOL7RcgMiss';
onsets{10}=[28.0];
durations{10}=[0];
names{11}='JOL8RcgHit';
onsets{11}=[24.0];
durations{11}=[0];
names{12}='Arrow';
onsets{12}=[120, 20];
durations{12}=[30, 30];
save s0215_r01_multiconds
clear

% next subject-run